{
	"version": 1540397783,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/abby_abby_body0-sheet0.png",
		"images/abby_abby_bodyoverride0-sheet0.png",
		"images/abby_abby_bodyoverride0-sheet1.png",
		"images/abby_abby_eye0-sheet0.png",
		"images/abby_abby_flower0-sheet0.png",
		"images/abby_abby_stuff1-sheet0.png",
		"images/abby_abby_arm_l0-sheet0.png",
		"images/abby_abby_arm_r0-sheet0.png",
		"images/abby-sheet0.png",
		"images/freebutton-sheet0.png",
		"images/freebutton-sheet1.png",
		"images/arrowbutton-sheet0.png",
		"images/arrowbutton-sheet1.png",
		"images/sprite-sheet0.png",
		"media/abbyvoice (1).ogg",
		"media/abbyvoice (2).ogg",
		"media/abbyvoice (3).ogg",
		"media/abbyvoice (4).ogg",
		"media/abbyvoice (5).ogg",
		"media/abbyvoice (6).ogg",
		"media/abbyvoice (7).ogg",
		"media/abbyvoice (8).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"abby.scml",
		"abby.scon"
	]
}