{
	"version": 1533849690,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/evehead-sheet0.png",
		"images/evehead-sheet1.png",
		"images/evebody-sheet0.png",
		"images/evebody-sheet1.png",
		"images/tear-sheet0.png",
		"images/tear-sheet1.png",
		"images/tearfx-sheet0.png",
		"images/tearfx-sheet1.png",
		"images/hpbage-sheet0.png",
		"images/hpbage-sheet1.png",
		"images/item-sheet0.png",
		"images/sprite-sheet0.png",
		"images/ghost-sheet0.png",
		"images/spike-sheet0.png",
		"images/bloodfx-sheet0.png",
		"images/bloodfx-sheet1.png",
		"media/splatter 0.m4a",
		"media/splatter 0.ogg",
		"media/tear fire 4.m4a",
		"media/tear fire 4.ogg",
		"media/tear fire 5.m4a",
		"media/tear fire 5.ogg",
		"media/hurt grunt .m4a",
		"media/hurt grunt .ogg",
		"media/hurt grunt 1.m4a",
		"media/hurt grunt 1.ogg",
		"media/hurt grunt 2.m4a",
		"media/hurt grunt 2.ogg",
		"media/isaac dies new.m4a",
		"media/isaac dies new.ogg",
		"media/diptera sonata(basement).ogg",
		"media/burning basement loop.ogg",
		"media/burning basement intro.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}